# Generated by Django 5.2.17 on 2026-08-21 15:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo'),
        ),
    ]
