# Generated by Django 5.2.17 on 2026-08-21 15:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_dentist_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
