# Generated by Django 5.2.17 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_galleryimage_image_url_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Family Dental Care', max_length=200)),
                ('tagline', models.CharField(default='Advanced Dental Care', max_length=200)),
                ('phone', models.CharField(default='+880 1711266608', max_length=50)),
                ('email', models.EmailField(default='info@familydentalcare.com', max_length=254)),
                ('address', models.TextField(default='Family Dental Care Clinic')),
                ('opening_hours', models.CharField(default='Sat – Thu: 9:00 AM – 9:00 PM', max_length=100)),
            ],
            options={
                'verbose_name': 'Clinic Setting',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
    ]
