# Generated by Django 5.2.17 on 2026-08-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_clinicsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload custom clinic logo image', null=True, upload_to='clinic/'),
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='logo_icon',
            field=models.CharField(default='🦷', help_text='Fallback emoji icon if no image logo is uploaded', max_length=10),
        ),
    ]
