# Generated by Django 5.2.17 on 2026-08-24 17:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinicsetting_logo_clinicsetting_logo_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsetting',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
