# Generated by Django 5.2.17 on 2026-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_clinicsetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsetting',
            name='map_url',
            field=models.URLField(blank=True, help_text='Paste custom Google Maps link (e.g., https://maps.google.com/...)', null=True),
        ),
    ]
